//! End-to-end availability tests over real mTLS.
//!
//! These tests run the actual tower pipeline (identity, admission, auth, rate
//! limit) behind a tonic server with a throwaway PKI generated by `rcgen`.
//! They are the transport-level regression for the certificate-bound rate
//! limiting and pre-auth admission controls (GCOB-001/003/007).

use std::net::SocketAddr;
use std::sync::Arc;

use tokio_stream::wrappers::ReceiverStream;
use tonic::transport::server::TcpIncoming;
use tonic::transport::{
    Certificate, Channel, ClientTlsConfig, Endpoint, Identity, Server, ServerTlsConfig,
};
use tonic::{Request, Response, Status};

use crate::cln::client::ClnClient;
use crate::cln::cln_api;
use crate::cln::cln_api::node_services_client::NodeServicesClient;
use crate::cln::cln_api::node_services_server::{NodeServices, NodeServicesServer};
use crate::grpc::interceptors::admission_layer::AdmissionLayer;
use crate::grpc::interceptors::auth_layer::AuthLayer;
use crate::grpc::interceptors::identity::ClientIdentityLayer;
use crate::grpc::interceptors::rate_limit_layer::RateLimitLayer;
use crate::grpc::interceptors::rate_limiter::InMemoryRateLimiter;
use crate::grpc::limits::Limits;

// --- Fake backend ---

#[derive(Clone)]
struct FakeNodeServices;

#[tonic::async_trait]
impl NodeServices for FakeNodeServices {
    async fn invoice(
        &self,
        _request: Request<cln_api::InvoiceRequest>,
    ) -> Result<Response<cln_api::InvoiceResponse>, Status> {
        Ok(Response::new(cln_api::InvoiceResponse::default()))
    }

    async fn getinfo(
        &self,
        _request: Request<cln_api::GetinfoRequest>,
    ) -> Result<Response<cln_api::GetinfoResponse>, Status> {
        Ok(Response::new(cln_api::GetinfoResponse::default()))
    }

    async fn xpay(
        &self,
        _request: Request<cln_api::XpayRequest>,
    ) -> Result<Response<cln_api::XpayResponse>, Status> {
        Ok(Response::new(cln_api::XpayResponse::default()))
    }

    type InvoiceStreamStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn invoice_stream(
        &self,
        _request: Request<cln_api::InvoiceRequest>,
    ) -> Result<Response<Self::InvoiceStreamStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }

    type XpayStreamWatchStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn xpay_stream_watch(
        &self,
        _request: Request<cln_api::XpayRequest>,
    ) -> Result<Response<Self::XpayStreamWatchStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }

    type XpayStreamStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn xpay_stream(
        &self,
        _request: Request<()>,
    ) -> Result<Response<Self::XpayStreamStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }

    type InvoiceWatchStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn invoice_watch(
        &self,
        _request: Request<()>,
    ) -> Result<Response<Self::InvoiceWatchStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }

    type WatchChannelsStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn watch_channels(
        &self,
        _request: Request<()>,
    ) -> Result<Response<Self::WatchChannelsStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }

    type WatchPeersStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn watch_peers(
        &self,
        _request: Request<()>,
    ) -> Result<Response<Self::WatchPeersStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }

    type WatchSystemStream = ReceiverStream<Result<cln_api::Event, Status>>;

    async fn watch_system(
        &self,
        _request: Request<()>,
    ) -> Result<Response<Self::WatchSystemStream>, Status> {
        unimplemented!("not exercised by the availability tests")
    }
}

// --- Throwaway PKI ---

struct TestPki {
    ca_pem: String,
    server_cert_pem: String,
    server_key_pem: String,
    /// (certificate PEM, private key PEM) per logical client.
    clients: Vec<(String, String)>,
}

fn generate_pki(client_count: usize) -> TestPki {
    use rcgen::{
        BasicConstraints, CertificateParams, CertifiedIssuer, ExtendedKeyUsagePurpose, IsCa,
        KeyPair, KeyUsagePurpose,
    };

    let mut ca_params = CertificateParams::new(Vec::<String>::new()).unwrap();
    ca_params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
    ca_params.key_usages = vec![KeyUsagePurpose::KeyCertSign, KeyUsagePurpose::CrlSign];
    let ca_key = KeyPair::generate().unwrap();
    let ca = CertifiedIssuer::self_signed(ca_params, ca_key).unwrap();

    let mut server_params = CertificateParams::new(vec!["localhost".to_string()]).unwrap();
    server_params.key_usages = vec![KeyUsagePurpose::DigitalSignature];
    server_params.extended_key_usages = vec![ExtendedKeyUsagePurpose::ServerAuth];
    let server_key = KeyPair::generate().unwrap();
    let server_cert = server_params.signed_by(&server_key, &ca).unwrap();

    let mut clients = Vec::new();
    for i in 0..client_count {
        let mut params = CertificateParams::new(vec![format!("client-{i}.test")]).unwrap();
        params.key_usages = vec![KeyUsagePurpose::DigitalSignature];
        params.extended_key_usages = vec![ExtendedKeyUsagePurpose::ClientAuth];
        let key = KeyPair::generate().unwrap();
        let cert = params.signed_by(&key, &ca).unwrap();
        clients.push((cert.pem(), key.serialize_pem()));
    }

    TestPki {
        ca_pem: ca.pem(),
        server_cert_pem: server_cert.pem(),
        server_key_pem: server_key.serialize_pem(),
        clients,
    }
}

fn server_tls(pki: &TestPki) -> ServerTlsConfig {
    ServerTlsConfig::new()
        .identity(Identity::from_pem(
            &pki.server_cert_pem,
            &pki.server_key_pem,
        ))
        .client_ca_root(Certificate::from_pem(&pki.ca_pem))
}

async fn bind() -> (tokio::net::TcpListener, SocketAddr) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    (listener, addr)
}

/// Connect the client `index` of the PKI to `addr`, verifying the server as
/// `localhost` while connecting to the loopback address.
async fn connect_client(
    pki: &TestPki,
    index: usize,
    addr: SocketAddr,
) -> NodeServicesClient<Channel> {
    let (cert, key) = &pki.clients[index];
    let tls = ClientTlsConfig::new()
        .ca_certificate(Certificate::from_pem(&pki.ca_pem))
        .identity(Identity::from_pem(cert, key))
        .domain_name("localhost");

    let channel = Endpoint::from_shared(format!("https://127.0.0.1:{}", addr.port()))
        .unwrap()
        .tls_config(tls)
        .unwrap()
        .connect()
        .await
        .expect("mTLS connection must succeed");

    NodeServicesClient::new(channel)
}

fn xpay_request(claim: &str) -> Request<cln_api::XpayRequest> {
    let mut request = Request::new(cln_api::XpayRequest::default());
    request
        .metadata_mut()
        .insert("x-rune", "test-rune".parse().unwrap());
    request
        .metadata_mut()
        .insert("x-client-id", claim.parse().unwrap());
    request
}

fn getinfo_request() -> Request<cln_api::GetinfoRequest> {
    let mut request = Request::new(cln_api::GetinfoRequest::default());
    request
        .metadata_mut()
        .insert("x-rune", "test-rune".parse().unwrap());
    request
}

/// ClnClient pointing at a closed port: `check_rune` fails fast.
fn unreachable_cln() -> Arc<ClnClient> {
    let channel = Endpoint::from_static("http://127.0.0.1:1").connect_lazy();
    Arc::new(ClnClient {
        inner: cln_api::node_client::NodeClient::new(channel),
        node_id: "test-node".to_string(),
    })
}

// --- Tests ---

/// GCOB-001: over real mTLS, one certificate cannot mint budgets by renaming
/// the `x-client-id` header.
#[tokio::test]
async fn spoofed_claims_share_one_certificate_budget_over_mtls() {
    let pki = generate_pki(1);
    let (listener, addr) = bind().await;

    let server = Server::builder()
        .tls_config(server_tls(&pki))
        .unwrap()
        // First layer added is the outermost.
        .layer(ClientIdentityLayer::new())
        .layer(RateLimitLayer::new(None, InMemoryRateLimiter::new()))
        .add_service(NodeServicesServer::new(FakeNodeServices));
    let handle = tokio::spawn(async move {
        let _ = server
            .serve_with_incoming(TcpIncoming::from(listener))
            .await;
    });

    let mut client = connect_client(&pki, 0, addr).await;

    for i in 0..3 {
        let response = client.xpay(xpay_request(&format!("claim-{i}"))).await;
        assert!(response.is_ok(), "request {i} must pass: {response:?}");
    }

    let rejected = client.xpay(xpay_request("claim-3")).await.unwrap_err();
    assert_eq!(rejected.code(), tonic::Code::ResourceExhausted);

    handle.abort();
}

/// Different client certificates keep independent budgets.
#[tokio::test]
async fn different_certificates_have_independent_budgets_over_mtls() {
    let pki = generate_pki(2);
    let (listener, addr) = bind().await;

    let server = Server::builder()
        .tls_config(server_tls(&pki))
        .unwrap()
        // First layer added is the outermost.
        .layer(ClientIdentityLayer::new())
        .layer(RateLimitLayer::new(None, InMemoryRateLimiter::new()))
        .add_service(NodeServicesServer::new(FakeNodeServices));
    let handle = tokio::spawn(async move {
        let _ = server
            .serve_with_incoming(TcpIncoming::from(listener))
            .await;
    });

    let mut client_a = connect_client(&pki, 0, addr).await;
    let mut client_b = connect_client(&pki, 1, addr).await;

    for i in 0..3 {
        let response = client_a.xpay(xpay_request(&format!("a-{i}"))).await;
        assert!(response.is_ok(), "certificate A request {i}: {response:?}");
    }
    let rejected = client_a.xpay(xpay_request("a-3")).await.unwrap_err();
    assert_eq!(rejected.code(), tonic::Code::ResourceExhausted);

    let allowed = client_b.xpay(xpay_request("b-0")).await;
    assert!(
        allowed.is_ok(),
        "certificate B must keep its own budget: {allowed:?}"
    );

    handle.abort();
}

/// GCOB-003: the pre-auth budget runs before `check_rune`, so requests beyond
/// it are cut with RESOURCE_EXHAUSTED and never reach the auth layer.
#[tokio::test]
async fn preauth_budget_cuts_before_rune_validation_over_mtls() {
    let pki = generate_pki(1);
    let (listener, addr) = bind().await;

    let limits = Limits {
        preauth_limit: 2,
        preauth_window_seconds: 60,
        ..Limits::default()
    };
    let admission = AdmissionLayer::new(None, InMemoryRateLimiter::new(), &limits);
    let auth = AuthLayer::new(unreachable_cln(), 262_144);

    let server = Server::builder()
        .tls_config(server_tls(&pki))
        .unwrap()
        // First layer added is the outermost.
        .layer(ClientIdentityLayer::new())
        .layer(admission)
        .layer(auth)
        .add_service(NodeServicesServer::new(FakeNodeServices));
    let handle = tokio::spawn(async move {
        let _ = server
            .serve_with_incoming(TcpIncoming::from(listener))
            .await;
    });

    let mut client = connect_client(&pki, 0, addr).await;

    for i in 0..2 {
        let status = client.getinfo(getinfo_request()).await.unwrap_err();
        // Passed admission and reached `check_rune`, which cannot connect.
        assert_eq!(
            status.code(),
            tonic::Code::Unauthenticated,
            "request {i}: {status:?}"
        );
    }

    for i in 2..4 {
        let status = client.getinfo(getinfo_request()).await.unwrap_err();
        assert_eq!(
            status.code(),
            tonic::Code::ResourceExhausted,
            "request {i} must be cut pre-auth: {status:?}"
        );
    }

    handle.abort();
}

/// GCOB-007: oversized bodies are rejected before rune validation.
#[tokio::test]
async fn oversized_body_is_rejected_over_mtls() {
    let pki = generate_pki(1);
    let (listener, addr) = bind().await;

    let auth = AuthLayer::new(unreachable_cln(), 64);
    let server = Server::builder()
        .tls_config(server_tls(&pki))
        .unwrap()
        // First layer added is the outermost.
        .layer(ClientIdentityLayer::new())
        .layer(auth)
        .add_service(NodeServicesServer::new(FakeNodeServices));
    let handle = tokio::spawn(async move {
        let _ = server
            .serve_with_incoming(TcpIncoming::from(listener))
            .await;
    });

    let mut client = connect_client(&pki, 0, addr).await;

    let oversized = cln_api::XpayRequest {
        invstring: "x".repeat(256),
        ..Default::default()
    };
    let status = client
        .xpay(xpay_request_with_body(oversized))
        .await
        .unwrap_err();
    assert_eq!(status.code(), tonic::Code::ResourceExhausted);

    // A small body passes the size gate and reaches rune validation.
    let small = cln_api::XpayRequest {
        invstring: "lnbc1small".to_string(),
        ..Default::default()
    };
    let status = client
        .xpay(xpay_request_with_body(small))
        .await
        .unwrap_err();
    assert_eq!(status.code(), tonic::Code::Unauthenticated);

    handle.abort();
}

fn xpay_request_with_body(body: cln_api::XpayRequest) -> Request<cln_api::XpayRequest> {
    let mut request = Request::new(body);
    request
        .metadata_mut()
        .insert("x-rune", "test-rune".parse().unwrap());
    request
}
